In [16]:
#Excercise 1
#QP 1
#Write a numpy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

import numpy as np
a=np.arange(0,21)
print("Original")
print(a)
print("New")
matrix1=[]
for i in range(9,15):
    if i >= 9 & i<=15:
        a[i]=-a[i]
print(a)


Original
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
New
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14  15  16  17
  18  19  20]


In [28]:
#QP 2
#Write a numpy program to compute sum of all elements, sum of each column and sum of each row of a given array

import numpy as np

# Define a 2D array (matrix)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute the sum of all elements
total_sum = np.sum(array)

# Compute the sum of each column
column_sum = np.sum(array, axis=0)

# Compute the sum of each row
row_sum = np.sum(array, axis=1)

# Print the results
print("Array:")
print(array)

print("\nSum of all elements:")
print(total_sum)

print("\nSum of each column:")
print(column_sum)

print("\nSum of each row:")
print(row_sum)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all elements:
45

Sum of each column:
[12 15 18]

Sum of each row:
[ 6 15 24]


In [36]:
#Q 3
#Write a numpy program to save a given array to a text file and load it

f1=np.arange(10)
np.savetxt('newarray.txt',f1,fmt='%d')
ar=np.loadtxt('newarray.txt',dtype=int)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
#Q 4
#Write a numpy program to check whether two arrays are equal or not

array1=np.array([1,2,3])
array2=np.array([3,2,1])

e=np.array_equal(array1,array2)
if e:
    print("Yes")
else:
    print("No")

No


In [48]:
#Q 5
#Write a numpy program to create a 4x4 array with random values, create a new array from the said array by swapping first and last rows

array=np.random.rand(4,4)
print("Array")
print(array)

swap_array=array[[3,1,2,0],:]
print("New")
print(swap_array)

Array
[[0.99902012 0.41996354 0.17999862 0.09279124]
 [0.05374882 0.08080988 0.46458884 0.63369908]
 [0.53570851 0.90386502 0.34093826 0.35307574]
 [0.0978626  0.3481367  0.75426284 0.8766061 ]]
New
[[0.0978626  0.3481367  0.75426284 0.8766061 ]
 [0.05374882 0.08080988 0.46458884 0.63369908]
 [0.53570851 0.90386502 0.34093826 0.35307574]
 [0.99902012 0.41996354 0.17999862 0.09279124]]


In [62]:
#Q 6
#Numpy program to multiply two given arrays of same size, element by element
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print("First array")
print(arr1)
arr2=np.array([[9,10,11,12],[13,14,15,16]])
print("\nSecond array")
print(arr2)

ans=np.multiply(arr1,arr2)
print("\nResult")
print(ans)

First array
[[1 2 3 4]
 [5 6 7 8]]

Second array
[[ 9 10 11 12]
 [13 14 15 16]]

Result
[[  9  20  33  48]
 [ 65  84 105 128]]
