In [56]:
import numpy as np
a=np.array([1,2,3,5])
print (a)
b=np.array([[1,2,5,4],[1,3,4,3],[6,7,8,7]])
print (b)


[1 2 3 5]
[[1 2 5 4]
 [1 3 4 3]
 [6 7 8 7]]


In [28]:
print (b.shape)


(3, 3)


In [30]:
print (a.shape)


(3,)


In [46]:
c=b.reshape(4,3)
print(c)

[[1 2 5]
 [4 1 3]
 [4 3 6]
 [7 8 7]]


In [52]:
b.shape=(6,2)
print (b)

[[1 2]
 [5 4]
 [1 3]
 [4 3]
 [6 7]
 [8 7]]


In [58]:
a.shape=(2,2)
print (a)

[[1 2]
 [3 5]]


In [60]:
x=np.arange(10)
print (x)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
y=np.arange(1,24,2,dtype=float)
print (y)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23.]


In [66]:
print (a[0])

[1 2]


In [78]:
q=np.array([1,2,3,4,5])
s=np.array([2,3,1,4,5])
print(np.less(q,s))
print(np.greater(q,s))
print(np.greater_equal(q,s))
print(np.less_equal(q,s))
print(np.equal(q,s))
print(np.not_equal(q,s))


[ True  True False False False]
[False False  True False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False False  True  True]
[ True  True  True False False]


In [80]:
e=np.arange(50,91,2)
print(e)

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90]


In [84]:
k=np.identity(4)
print(k)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [94]:
p=np.diag([1,2,3,4,5])
print(p)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [102]:
arr = np.identity(3, dtype=complex,)
print(arr)

[[1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j]]
