In [7]:
import numpy as np
m1=np.array([[1,2],[3,4]])
print(m1)

array([[1, 2],
       [3, 4]])

In [9]:
m2=np.array([[5,6],[7,8]])
print(m2)

array([[5, 6],
       [7, 8]])

In [11]:
a=np.linalg.inv(m2)
print(a)

[[-4.   3. ]
 [ 3.5 -2.5]]


In [19]:
a=np.dot(m2,m1)
print(a)

[[23 34]
 [31 46]]


In [29]:
a=np.transpose(m1)
print(a)

[[1 3]
 [2 4]]


In [33]:
b=m1.flatten()
print(b)

[1 2 3 4]


In [35]:
#read matrix from user
matrix=[]
for i in range(2):
    row=[]
    for j in range(2):
        a=int(input())
        row.append(a)
    matrix.append(row)
print(matrix)


 1
 2
 3
 3


[[1, 2], [3, 3]]


In [39]:
c=np.transpose(matrix)
print (c)

[[1 3]
 [2 3]]


In [43]:
#read rows and columns from user
matrix1=[]
a1=int(input("Enter the no rows : "))
b1=int(input("Enter the no of columns :"))
for i in range(a1):
    row=[]
    for j in range(b1):
        c1=int(input("Enter elements : "))
        row.append(c1)
    matrix1.append(row)
print(matrix1)

Enter the no rows :  2
Enter the no of columns : 2
Enter elements :  1
Enter elements :  2
Enter elements :  3
Enter elements :  4


[[1, 2], [3, 4]]


In [49]:
#another way to create a matrix
matrix2=[]
a2=int(input("Enter the no rows : "))
b2=int(input("Enter the no of columns :"))
a=list(map(int,input().split()))
matrix2=np.array(a).reshape(a2,b2)
print(matrix2)

Enter the no rows :  2
Enter the no of columns : 2
 1 2 3 4


[[1 2]
 [3 4]]
